name: release
on:
  push:
    branches:
    - main_ish
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          asset_name: handlr

    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable

    - name: Test
      run: cargo test

    - name: build
      run: cargo build --release --locked

    # rust build already strips (because `strip = true`)
    # - name: Strip binary
    #   run: strip target/release/handlr

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/handlr
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
    